// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import Button from './Button/index.svelte';
import Cta from './Cta/index.svelte';
import Hero from './Hero/index.svelte';
import Locations from './Locations/index.svelte';
import Showcase from './Showcase/index.svelte';
import Programs from './Programs/index.svelte';
import RichText from './RichText/index.svelte';
import Staff from './Staff/index.svelte';

export const components = {
	bento: Bento,
	button: Button,
	cta: Cta,
	hero: Hero,
	locations: Locations,
	news_item: Showcase,
	programs: Programs,
	rich_text: RichText,
	staff: Staff
};
